version: '3.8'

services:
  # First OMNIX node - will likely become leader
  node1:
    build: .
    container_name: omnix-node1
    environment:
      - NODE_ID=node1
      - NODE_PORT=8080
      - RUST_LOG=info,omnix=debug
    ports:
      - "8080:8080"
      - "9080:9090"  # Metrics port
    volumes:
      - ./examples:/examples:ro
      - node1-data:/data
    networks:
      - omnix-net
    command: >
      /usr/local/bin/omnix run 
      -i /examples/counter_cluster_mvp.omx
      --node-id node1
      --port 8080
      -v

  # Second OMNIX node
  node2:
    build: .
    container_name: omnix-node2
    environment:
      - NODE_ID=node2
      - NODE_PORT=8081
      - RUST_LOG=info,omnix=debug
    ports:
      - "8081:8081"
      - "9081:9090"
    volumes:
      - ./examples:/examples:ro
      - node2-data:/data
    networks:
      - omnix-net
    depends_on:
      - node1
    command: >
      /usr/local/bin/omnix run
      -i /examples/counter_cluster_mvp.omx
      --node-id node2
      --port 8081
      -v

  # Third OMNIX node
  node3:
    build: .
    container_name: omnix-node3
    environment:
      - NODE_ID=node3
      - NODE_PORT=8082
      - RUST_LOG=info,omnix=debug
    ports:
      - "8082:8082"
      - "9082:9090"
    volumes:
      - ./examples:/examples:ro
      - node3-data:/data
    networks:
      - omnix-net
    depends_on:
      - node1
      - node2
    command: >
      /usr/local/bin/omnix run
      -i /examples/counter_cluster_mvp.omx
      --node-id node3
      --port 8082
      -v

  # Optional: Prometheus for metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: omnix-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - omnix-net
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  # Optional: Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: omnix-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=omnix
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./monitoring/grafana:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - omnix-net
    depends_on:
      - prometheus

networks:
  omnix-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  node1-data:
  node2-data:
  node3-data:
  prometheus-data:
  grafana-data: