[package]
name = "omnix-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.13"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
thiserror = "1.0"
indexmap = "2.0"
petgraph = "0.6"