[package]
name = "omnix-consensus"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
ed25519-dalek = "2.0"
rand = "0.8"
